jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ssm
  username: root
  password: innosen

server:
  port: 80

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mydql://localhost:3306/ssm
#    username: root
#    password: innosen

mybatis:
  type-aliases-package: com.w2x.springboot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
